### ISSUE TITLE
Creating packet without data

### ISSUE THREAD

**Issue by mohammadhasanzadeh** [hideakitai/Packetizer#1]
Is there any way for creating packet without data (with zero length)?
I just need `index` byte.

**Comment by hideakitai** [comment]
@mohammadhasanzadeh  Sorry for late reply.There is no way to create packet like that.
If you want only index byte (only 1byte?), I recommend to send data simpler. For example,

- Byte 0: 0xFF (Header)
- Byte 1: Index (0x00 - 0xFD)
- Byte2 : 0xFE (Footer, If you need)

That's enough and you don't need to use this library. 
Thank you for the feedback!!
