### ISSUE TITLE
Please update platform.io registry.

### ISSUE THREAD

**Issue by ktetsuo** [hideakitai/Packetizer#13]
The latest version of this library is 0.8.3, but the version at platform.io is 0.4.5.

https://registry.platformio.org/libraries/hideakitai/Packetizer
![image](https://github.com/user-attachments/assets/a8137fb1-4cfe-4b8c-8ebb-8a8d5a2903c8)

I would like to use this library with MsgPacketizer by platform.io, but Packetizer 0.4.5 does not support network.

**Comment by hideakitai** [comment]
I don't know why but re-published the latest v0.8.3

https://registry.platformio.org/libraries/hideakitai/Packetizer
