### ISSUE TITLE
Crash on CRCPP::CRC::CalculateRemainder

### ISSUE THREAD

**Issue by drewhamiltonasdf** [hideakitai/Packetizer#2]
Hi there,

Packetizer has been crashing on me quite a bit recently. Using a just-in-time debugger, I have narrowed it down (I think) to Line 651 of CRCpp.h, which is throwing an "Access Violations "reading location 0x004B1918". Line 651 is the line starting with "remainder =" below...

```cpp
        while (size--)
        {
            remainder = static_cast<CRCType>(remainder ^ (static_cast<CRCType>(*current++) << SHIFT));
```

If you have any suggestions for how I might fix this let me know!

Many thanks,
Drew Hamilton

**Comment by drewhamiltonasdf** [comment]
This is torturing me.

**Comment by hideakitai** [comment]
I saw the issue on CRCpp.

https://github.com/d-bahr/CRCpp/issues/16

> I took a brief look at MsgPacketizer and I didn't see anything out of the ordinary

So I think it's not the problem of this library. I have no problem with my environment/code. If you still have the problem, please reopen the issue.
