### ISSUE TITLE
Bug in CRC calculation range; either in README or Implementation

### ISSUE THREAD

**Issue by kpochwala** [hideakitai/Packetizer#3]
Hi, there seems to be a bug in the README. It says that the CRC is calculated from the whole packet (together with the ID), while in the `Encoding.h` the CRC is calculated without it. It took me a while to find this bug while writing a Python implementation, so I'll leave the issue for you, others, and... myself in the future. 

By the way, maybe it would be worth to enable/disable ID and CRC in MsgPacketizer, as it is possible in here - I found this bug using MsgPacketizer.

Here is the quote from README:

```
### Index and CRC8 Option

You can optionally add index byte to idetify packet type, and crc8 byte to verify packet structure.
These options are disabled by default.
If you use them, original data array is modified like:

| index  | data    | crc8   |
| ------ | ------- | ------ |
| 1 byte | N bytes | 1 byte |

CRC8 will be calcurated including index byte.
After that, these byte arrays will be coverted to COBS / SLIP encoding.
```

And (even commented :) ) lines in implementation:
https://github.com/hideakitai/Packetizer/blob/master/Packetizer/Encoding.h#L34C1-L34C103
https://github.com/hideakitai/Packetizer/blob/master/Packetizer/Encoding.h#L47C9-L47C9

**Comment by hideakitai** [comment]
Fixed. Thank you so much!
